### ISSUE TITLE
Checklist workshop 6

### ISSUE THREAD

**Issue by ebbabrage** [Sneakycloud/Priority-calculator#10]
### Part 1 - Versioning, Releases and Continuous Delivery (CD)
- [x] Make your first release v0.1.0 by creating a tag through git.
- [x] Generate [an artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) through CI.  This can be anything that makes sense to your project: an executable file, a code coverage report, an installer for the built version, etc.
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [x] (Optional) (if your project is a "desktop" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), a release artifact is generated: this may be a simple executable or an installer

### Part 2 - DevOps
- [x] List the issues and PRs you worked on during the week 
- [x] Define a few project goals for the upcoming weeks, create them as issues, list them 
- [x] Make a new release following Semantic Versioning rules

**Comment by Sneakycloud** [comment]
Issues done by me:
#66

**Comment by ebbabrage** [comment]
Goals for the upcoming weeks:
#69 
#71 
#72 
#73 
#74 
#75 
#76 
#77 
#78 
#79

**Comment by mtaromi** [comment]
> Goals for the upcoming weeks: #69 #71 #72 #73 #74 #75 #76 #77 #78 #79

Please describe goals here also.

**Comment by ebbabrage** [comment]
First part is mainly done in checklist workshop 5.

Pull request for first release https://github.com/Sneakycloud/Priority-calculator/pull/80

Tag for first release [v0.1.0](https://github.com/Sneakycloud/Priority-calculator/releases/tag/v0.1.0)

The final change in the workflow file for generating an exe https://github.com/Sneakycloud/Priority-calculator/commit/08022b93bc5de6891acc255d258092aaa9c2e833
First commit which autogenerated an exe https://github.com/Sneakycloud/Priority-calculator/commit/df0d1006a1ed787abbb7fb6d2b005c62f7b4a2b3

**Comment by sandzan** [comment]
Issue: #97 
Commit: 3a9d6fce652a6107c41193ac29ac6f012a2fe6c6
PR: a51272acba87a2494f6be32f2bf6dc6177df4fae

**Comment by ebbabrage** [comment]
A new release 0.2.0: https://github.com/Sneakycloud/Priority-calculator/releases/tag/v0.2.0

**Comment by mtaromi** [comment]
@Sneakycloud, @sodqv, @ebbabrage, and @sandzan

Well done! You seem to fulfill all the items in the checklist. 

I am now closing this issue.
