### ISSUE TITLE
Checklist workshop 7

### ISSUE THREAD

**Issue by ebbabrage** [Sneakycloud/Priority-calculator#11]
- [ ] Create an issue titled "Lecture 12 checklist" to track these checklist items
- [ ] Project has a software license
- [ ] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [ ] [Optional] Present your project at the Lab session on May 6. (something simple: 5 to 10 minutes)

**Comment by Sneakycloud** [comment]
Unit tests #66  (I do not have the energy to link to every unit test i have written)

**Comment by ebbabrage** [comment]
My unit tests with matching PR:
Unit test 9d43896f2764206feca440f2c4a6d22bc8a30b61
Unit test e82cb6ce7ba432d442281b9b542c93bdfda60ff5
PR #103

**Comment by sandzan** [comment]
My unit tests
2e167cf756ddc210b9a08fa2b6dc9e88d9d9af4b
56d33915a90f35b8494ea525c0c72a9ecc933e59
PR: #108

**Comment by ebbabrage** [comment]
Integration test latest uppdate 0bd285cb24a5760c64997eccf0fb8c9bf01f5b93
PR #110

**Comment by Sneakycloud** [comment]
Code coverage increase:
57.5% at commit: 00474c2f90213342daec32a3432e9cb7cc2cdea5
81.4% at commit: 84078a5
An increase of 23.9%

**Comment by sandzan** [comment]
Non-functional testing is done while debugging in Visual Studio. Buy using **Diagnostic Tools** we can see how the Process Memory and CPU are doing. If we want to analyse the CPU closer you can click **Record CPU Profile** and when the debugging is done we can find it under **Debug>Window>Show Diagnostic Tools** and then **CPU Usage**.

**Comment by mtaromi** [comment]
@Sneakycloud, @sodqv, @ebbabrage, and @sandzan

I have reviewed the items for Workshop 7 and you seem to fulfill all the items. Good job! 

I am closing this issue.
