### ISSUE TITLE
Checklist workshop 2

### ISSUE THREAD

**Issue by ebbabrage** [Sneakycloud/Priority-calculator#6]
- [x] Create few issues on using GRASP which are “closed” with an associated implementation (code or documentation in the code, explaining how/what a particular pattern is addressed).
- [x] Add a `.gitignore` file to your project
- [x] Have a revert commit (don't edit history: create a new revert commit!)
- [x] Have a branch implementing a small feature
- [x] Have a merge commit (of the branch)
- [x] Have a branch of conflict with main/master
- [x] Try to merge and resolve the merge conflict
- [x] Have a working compilation and running instructions in README
- [x] Have issuses associated with each of your changes

**Comment by Sneakycloud** [comment]
The commits in which checklist points 2,3,4 happend.
2. Revert commit 96f49755ad6154b139983d1ba697064600dbe8c4 .
3. Implementation of shunting yard commit 167bdc814caae1c052e6fb6fa7043f7a0a8a6371 .
4. Merge of backend branch implementing shuting yard to main commit 2309fd0a57ed0197fbbf1343e26434c69ad7917a .

**Comment by sandzan** [comment]
GRASP issues: #35 and #36

**Comment by sandzan** [comment]
Conflict in GUI 92795d3aaccc841c0a5ada4c718ed112441b702c
Conflict in main af8de91b4547e9e814438d6e80c9b2ee51b4059e
FIxed merge conflict with commit 1e6b65d45616aa97c482bf46238fa8a670a3da8c

**Comment by sandzan** [comment]
Working compilation instructions #37

**Comment by mtaromi** [comment]
Very neat! You seem to fulfill all the items. Good job! 🎉

I am closing this issue.
