### ISSUE TITLE
Checklist workshop 3

### ISSUE THREAD

**Issue by ebbabrage** [Sneakycloud/Priority-calculator#7]
Part one
- [x] Have a unit test
- [x] Have several unit tests of differnt features and modules
- [x] Test are passing on the `master`/`main` branch
- [x] README with instructions of how to run unit tests
- [x] README with instructions of how to generate code coverage informations for units tests
- [x] README with instructions of how to run a linter for your project
- [x] If using assets found onlie explicitly list them in the README

Part two
- [x] Continuous integration (CI) through GitHub Actions
- [x] CI checs that your code compile or parses
- [x] CI checkt that the unit tests are passing
- [x] `master`/`main` is passing / green
- [x] CI "badge" on README
 
Optional items if you want to work the extra mile
- [ ] CI produces code coverage information
- [ ] CI preforms lint checks

**Comment by ebbabrage** [comment]
Commit b918606e0fb41217a5957af48cb8e085af3de5b4 handles implementation of Linter

**Comment by ebbabrage** [comment]
Unit test is handled by commits:
fcfbc9ab3d01fc4be0750b340de7991de52a8d3b
c66b0a7327cebbed89dc2ba0f595cbdae043ca92

**Comment by ebbabrage** [comment]
CI bagdge added by commit:
00ad29acf334620c075ebbb8894f7f88217c8d32

**Comment by ebbabrage** [comment]
CI implementations is handled by commit:
580796bb74ded5049c554440e3bc5dd070fff7e7
