### ISSUE TITLE
Checklist workshop 4

### ISSUE THREAD

**Issue by ebbabrage** [Sneakycloud/Priority-calculator#8]
- [x] Your project have pull request and code review
- [x] Each student has created at least one pull request
- [x] Each student has preformed at least one code review
- [x] Each student has merged his own pull request after the code review
- [x] `master`/`main` is passing / green (and should be **always** from now on!)

**Comment by ebbabrage** [comment]
ebbabrage made oull request and merge in commit 687676afc30ee7126d6fdd38d09dc6c44b881190

**Comment by mtaromi** [comment]
@Sneakycloud, @sodqv, @ebbabrage, and @sandzan 

I have reviewed the items for Workshop 4, and you seem to fulfill all the items and neatly mention the corresponding commits. Good job! 🎉


I am closing this issue.
