### ISSUE TITLE
Checklist workshop 5

### ISSUE THREAD

**Issue by ebbabrage** [Sneakycloud/Priority-calculator#9]
Part one
- [ ] Make your first release v0.1.0 by creating a tag through git.
- [ ] Generate [an artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) through CI.  This can be anything that makes sense to your project: an executable file, a code coverage report, an installer for the built version, etc.
- [ ] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [ ] (Optional) (if your project is a "desktop" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), a release artifact is generated: this may be a simple executable or an installer
- [ ] (Optional) (if your project is a "web" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), the application is deployed on a (testing) server

Par two
- [ ] Carry on with your implementation adding more features to your project: use issues and PRs to track your work; add unit tests when appropriate.

**Comment by Sneakycloud** [comment]
Delivering software comes with a myriad of problems but a significant part is caused by human error which makes the problems inconsistent and hard to discover. The authors of continuous integration regard the automation of the development,testing and deployment as of vital importance to delivering software which is consistent and reproducible. This rings true regardless of the project size but becomes a larger point of failure for larger projects.
This leads to the importance of configuration settings as they are as important as the source code itself but often go without any of the extensive tests that the code is exposed to. Configuration settings include the settings for the OS, third-party services and the application itself. A single misconfigured version for an external service or library could lead to unpredictable problems which are hard to reproduce and even harder to locate the cause. This is why automation is recommended as the scripts themselves serve as documentation for the exact configuration that the program was designed for without any room for misinterpretation.  Putting these scripts and external libraries into version control also ensures that the settings are correctly configured for applications version which always makes reverting to older versions of the software reliable. 
Continuous Integration (CI) supports automation by encouraging frequent commits, which helps catch errors early, minimizes merge conflicts and maintains a functional build throughout development. It also enforces the automated configuration settings which CI servers can use to build and test the changes allowing for a clear view of the current state of the project and if it can be deployed. This is very useful for all projects as it avoids “merge hell” which for larger projects can take weeks to complete and it can be discovered that different branches used different versions of third-party software.
Automated tests are another automatable and important aspect of development as they ensure that the project is not just buildable but fulfills the expected requirements.  They allow developers and testers to save time and focus on more complex tasks. By writing acceptance tests with input from customers, developers can align their work with customer needs from the outset, reducing rework and keeping the project on track. These can then be used as a measure of how complete a project is.
Version control systems are a cornerstone of modern code development as they allow for features such as management of teams,branching and reverting. DVCS have the additional benefits of being able to function offline and being able to cherry pick commits which allows for a thriving open source community. For simple projects branching may not be too big of a deal but as they grow in size merge conflicts become an ever growing problem. This leads to different branch patterns like mainline development, branch by feature and branch by team with different pros and cons. It is always a trade off between code management and parallel coding in opposition to using the practices of CI. 
1. Automating the software development processes makes it cheaper, better quality and faster to develop and avoids bugs creeping into production.
2. Managing configuration settings is as important as managing the source code.
3. Push and pull regularly to prevent large merge conflicts but do not push a broken build.
4. Tests should be thoroughly integrated with the development process from start to finish.
14. Always consider the cost of branching before doing it.

**Comment by Sneakycloud** [comment]
The final change in the workflow file for generating an exe 08022b93bc5de6891acc255d258092aaa9c2e833
First commit which autogenerated an exe df0d1006a1ed787abbb7fb6d2b005c62f7b4a2b3

**Comment by mtaromi** [comment]
@Sneakycloud, @sodqv, @ebbabrage, and @sandzan

Well done! You seem to fulfill all the items.

Just would you please explain how someone can access the generated artefact?

**Comment by Sneakycloud** [comment]
The .exe is accessible in the release tag. Steps:
1. Go to the repository code tab
2. Click on the latest release to which is on the right
3. There is an Calculator.exe among the listed files, download it to use the program.
